# Numpy

NumPy (Numerical Python) is a Python library that focuses on scientific computing. NumPy has the ability to create N-dimensional array objects, which are similar to lists in Python. The advantage of NumPy arrays compared to lists in Python is that they consume less memory and run time faster. NumPy also makes it easier for us in Linear Algebra, especially operations on Vectors (1-d arrays) and Matrix (2-d arrays).

## Install Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Impor library NumPy

In [2]:
import numpy as np

## Creating a Numpy array

For example, you have the following list:

In [3]:
list_angka = [1, 2, 3, 4, 5]

To convert the list above into a NumPy array, you can use the array() function:

In [4]:
import numpy as np

arr_angka = np.array(list_angka)
print(arr_angka)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


## Creating a Numpy tuple

Just like lists, tuples can also be converted into NumPy arrays. For example, you have the following tuple:

In [5]:
tuple_angka = (6, 7, 8, 9, 10)

Converting a tuple to a NumPy array is done in the same way as a list:

In [6]:
arr_tuple = np.array(tuple_angka)
print(arr_tuple)  # Output: [ 6  7  8  9 10]

[ 6  7  8  9 10]


In [7]:
# Cek datatype
print(type(arr_tuple))

<class 'numpy.ndarray'>


## Dimmension in Arrays

### 0-D Arrays

In [8]:
arr = np.array(42)

print(arr)

42


### 1-D Arrays

In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays

In [10]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D Arrays

In [11]:
arr = np.array([[[11,22,33], [44,55,66]], [[1,2,3], [4,5,6]]])

print(arr)

[[[11 22 33]
  [44 55 66]]

 [[ 1  2  3]
  [ 4  5  6]]]


### Check how many dimention the arrays have

In [12]:
a = np.array(3)
b = np.array([5,6,7])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Create an array with 5 dimensions and verify that it has 5 dimensions

In [16]:
arr_1 = np.array([1,2,3,4,5], ndmin=5)

print(arr_1)

[[[[[1 2 3 4 5]]]]]


In [17]:
print('Number of dimention :', arr_1.ndim)

Number of dimention : 5


## Get the first element from the following array

In [18]:
import numpy as np

arr = np.array([6,7,8])

print(arr[0])

6


## Get the second element from the following array

In [19]:
import numpy as np

arr = np.array([6,7,8])

print(arr[1])

7


## Get third and fourth elements and add them

In [21]:
arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


## Access the element on the first row, second column

In [22]:
arr = np.array([['a','b','c'], ['d','e','f']])

print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  b


## Access the element on the 2nd row, 5th column

In [23]:
arr = np.array([['a','b','c'], ['d','e','f']])

print('2nd element on 1st row: ', arr[1,1])

2nd element on 1st row:  e


## Access the 3rd element of the second array of the first array

In [24]:
arr = np.array([[['a','b','c'], ['d','e','f']], [['g','h','i'],['j','k','l']]])

print(arr[1,0,2])

i
